In [16]:
import pandas as pd
import numpy as np
import csv

In [4]:
df = pd.read_csv('tennis_2015.csv')

In [5]:
df.head(10)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2015-329,Tokyo,Hard,32,A,20151005,1,104527,1.0,NaN,...,1.0,2.0,2.0,71.0,46.0,33.0,10.0,10.0,2.0,5.0
1,2015-329,Tokyo,Hard,32,A,20151005,2,105147,NaN,WC,...,14.0,1.0,4.0,96.0,52.0,25.0,23.0,13.0,12.0,19.0
2,2015-329,Tokyo,Hard,32,A,20151005,3,105572,NaN,Q,...,7.0,15.0,7.0,128.0,74.0,60.0,27.0,18.0,9.0,11.0
3,2015-329,Tokyo,Hard,32,A,20151005,4,105311,NaN,NaN,...,6.0,9.0,5.0,85.0,42.0,27.0,21.0,13.0,4.0,8.0
4,2015-329,Tokyo,Hard,32,A,20151005,5,104468,3.0,NaN,...,6.0,0.0,5.0,61.0,33.0,24.0,10.0,10.0,1.0,5.0
5,2015-329,Tokyo,Hard,32,A,20151005,6,106210,NaN,NaN,...,8.0,10.0,0.0,50.0,32.0,24.0,9.0,10.0,0.0,3.0
6,2015-329,Tokyo,Hard,32,A,20151005,7,104871,NaN,NaN,...,0.0,8.0,5.0,43.0,22.0,15.0,7.0,6.0,5.0,8.0
7,2015-329,Tokyo,Hard,32,A,20151005,8,104180,NaN,NaN,...,4.0,4.0,5.0,46.0,19.0,15.0,9.0,8.0,2.0,5.0
8,2015-329,Tokyo,Hard,32,A,20151005,9,105332,NaN,NaN,...,13.0,3.0,5.0,73.0,49.0,37.0,10.0,13.0,1.0,4.0
9,2015-329,Tokyo,Hard,32,A,20151005,10,104571,NaN,NaN,...,5.0,4.0,0.0,46.0,27.0,15.0,10.0,9.0,1.0,5.0

In [19]:
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")

In [21]:
missing_values_table(df)

Your selected dataframe has 49 columns.
There are 32 columns that have missing values.

In [70]:
array = ['0']
df.loc[df['w_svpt'].isin(array)]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
387,2015-540,Wimbledon,Grass,128,G,20150629,72,105053,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1173,2015-6967,Shenzhen,Hard,28,A,20150928,23,104198,4.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1710,2015-6242,Winston-Salem,Hard,48,A,20150823,42,105449,13.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,2015-414,Hamburg,Clay,32,A,20150727,26,104312,4.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2199,2015-341,Metz,Hard,28,A,20150921,21,104259,5.0,WC,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
for cell in df['w_svpt']:
	if cell  == 0:
		print("zero in cell")

zero in cell
zero in cell
zero in cell
zero in cell
zero in cell

In [6]:
df = df[np.isfinite(df['w_svpt'])]

In [7]:
clean_df=df[(df != 0).all(1)]

In [8]:
clean_two_df = clean_df.replace({'surface':{'Hard': 1, 'Clay': 2, 'Grass': 3}})
clean_two_df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
1,2015-329,Tokyo,1,32,A,20151005,2,105147,NaN,WC,...,14.0,1.0,4.0,96.0,52.0,25.0,23.0,13.0,12.0,19.0
2,2015-329,Tokyo,1,32,A,20151005,3,105572,NaN,Q,...,7.0,15.0,7.0,128.0,74.0,60.0,27.0,18.0,9.0,11.0
3,2015-329,Tokyo,1,32,A,20151005,4,105311,NaN,NaN,...,6.0,9.0,5.0,85.0,42.0,27.0,21.0,13.0,4.0,8.0
7,2015-329,Tokyo,1,32,A,20151005,8,104180,NaN,NaN,...,4.0,4.0,5.0,46.0,19.0,15.0,9.0,8.0,2.0,5.0
8,2015-329,Tokyo,1,32,A,20151005,9,105332,NaN,NaN,...,13.0,3.0,5.0,73.0,49.0,37.0,10.0,13.0,1.0,4.0

In [4]:
df['winner_name'].unique()

array(['Stanislas Wawrinka', 'Tatsuma Ito', 'Austin Krajicek',
       'Joao Sousa', 'Gilles Simon', 'Jiri Vesely', 'Jeremy Chardy',
       'Gilles Muller', 'Benoit Paire', 'Marcos Baghdatis', 'Nick Kyrgios',
       'Roberto Bautista Agut', 'Marin Cilic', 'Steve Johnson',
       'Sam Querrey', 'Kei Nishikori', 'Alexander Zverev',
       'Nicolas Almagro', 'Grigor Dimitrov', 'John Millman', 'Jack Sock',
       'Fernando Verdasco', 'Leonardo Mayer', 'Federico Delbonis',
       'Steve Darcis', 'Tomas Berdych', 'Richard Gasquet',
       'Bastian Trinker', 'Paolo Lorenzi', 'Philipp Kohlschreiber',
       'Dusan Lajovic', 'Andreas Haider Maurer', 'Martin Klizan',
       'Fabio Fognini', 'Damir Dzumhur', 'Borna Coric', 'Aljaz Bedene',
       'Blaz Kavcic', 'Gael Monfils', 'Dominic Thiem', 'David Goffin',
       'Ivo Karlovic', 'Bernard Tomic', 'Jared Donaldson',
       'Jerzy Janowicz', 'Tommy Robredo', 'Thomaz Bellucci',
       'Thanasi Kokkinakis', 'Vasek Pospisil', 'Mardy Fish',
       'Andreas Seppi', 'Feliciano Lopez', 'Kevin Anderson',
       'Novak Djokovic', 'Alexandr Dolgopolov', 'Andy Murray',
       'Rafael Nadal', 'Roger Federer', 'John Isner', 'Milos Raonic',
       'Viktor Troicki', 'Jo Wilfried Tsonga', 'Victor Estrella',
       'Albert Ramos', 'Edouard Roger Vasselin', 'Lukas Rosol',
       'David Ferrer', 'Teymuraz Gabashvili', 'Roberto Carballes Baena',
       'Juan Monaco', 'Mikhail Kukushkin', 'Marcel Granollers',
       'Andrey Kuznetsov', 'Elias Ymer', 'Albert Montanes', 'Marsel Ilhan',
       'Pablo Andujar', 'Andrey Rublev', 'Santiago Giraldo',
       'Pablo Cuevas', 'Jarkko Nieminen', 'Daniel Gimeno Traver',
       'Jurgen Melzer', 'Diego Sebastian Schwartzman', 'Denis Istomin',
       'Ivan Dodig', 'Andrey Golubev', 'Pierre Hugues Herbert',
       'Ricardas Berankis', 'Matthew Ebden', 'Denis Kudla', 'Liam Broady',
       'Kenny De Schepper', 'Tommy Haas', 'James Ward', 'Dustin Brown',
       'Robin Haase', 'Nicolas Mahut', 'Adrian Mannarino',
       'Nikoloz Basilashvili', 'Samuel Groth', 'James Duckworth',
       'Alejandro Gonzalez', 'Nicolas Jarry', 'Gerald Melzer',
       'Alejandro Falla', 'Renzo Olivo', 'Horacio Zeballos',
       'Ernests Gulbis', 'Donald Young', 'Sergiy Stakhovsky',
       'Mikhail Youzhny', 'Radek Stepanek', 'Radu Albot',
       'Benjamin Becker', 'Mischa Zverev', 'Gianni Mina', 'Lucas Pouille',
       'Pablo Carreno Busta', 'Guillermo Garcia Lopez', 'Simone Bolelli',
       'Yen Hsun Lu', 'Peter Gojowczyk', 'Tim Smyczek', 'Ryan Harrison',
       'Malek Jaziri', 'Michael Berrer', 'Igor Sijsling', 'Victor Hanescu',
       'Carlos Berlocq', 'Hyeon Chung', 'Filip Krajinovic',
       'Jan Lennard Struff', 'Lukasz Kubot', 'Juan Martin Del Potro',
       'Julien Benneteau', 'Daniel Elahi Galan Riveros', 'Rajeev Ram',
       'Alexander Sarkissian', 'Marcelo Demoliner', 'Yuichi Sugita',
       'Alejandro Gomez GB42', 'Adrian Menendez Maceiras',
       'Marco Chiudinelli', 'Marius Copil', 'Illya Marchenko',
       'Florian Mayer', 'Evgeny Donskoy', 'Ruben Bemelmans',
       'Yoshihito Nishioka', 'Lleyton Hewitt', 'Zhizhen Zhang',
       'Hiroki Moriya', 'Yan Bai', 'Janko Tipsarevic', 'Nikola Mektic',
       'Blaz Rola', 'Joao Souza', 'Thiemo De Bakker', 'John Patrick Smith',
       'Jan Hernych', 'Lukas Lacko', 'Stephane Robert', 'Julian Reister',
       'Taylor Harry Fritz', 'Dudi Sela', 'Dennis Novak',
       'Paul Henri Mathieu', 'Go Soeda', 'Matthias Bachinger',
       'Marinko Matosevic', 'Christian Lindell', 'Facundo Arguello',
       'Facundo Bagnis', 'Guido Andreozzi', 'Daniel Brands', 'Taro Daniel',
       'Francis Tiafoe', 'Guido Pella', 'Jaume Munar', 'Luca Vanni',
       'Matteo Donati', 'Tobias Kamke', 'Lamine Ouahab', 'Arthur De Greef',
       'Aslan Karatsev', 'Michael Venus', 'Rui Machado', 'Ze Zhang',
       'Kyle Edmund', 'Andrea Arnaboldi', 'Daniel Munoz De La Nava',
       'Inigo Cervantes Huegun', 'Marco Cecchinato', 'Guilherme Clezar',
       'Jan Mertl', 'Aleksandr Nedovyesov', 'Henri Laaksonen',
       'Kimmer Coppejans', 'Darian King', 'Jose Hernandez',
       'Gonzalo Escobar', 'Emilio Gomez', 'Yong Kyu Lim',
       'Warit Sornbutnark', 'Di Wu', 'Jose Rubin Statham',
       'Seong Chan Hong', 'Yuki Bhambri', 'Somdev Devvarman',
       'Frederik Nielsen', 'Norbert Gombos', 'Adrian Ungur',
       'Laurynas Grigelis', 'Oliver Marach', 'Michal Przysiezny',
       'Amir Weintraub', 'Aljaz Radinski', 'Nik Razborsek',
       'Marat Deviatiarov', 'David Souto', 'Ricardo Rodriguez',
       'Luis David Martinez', 'Marcelo Arevalo', 'Alex Llompart',
       'Christian Garay', 'Daniel Garza', 'Hugo Dellien',
       'Christian Garin', 'Hans Podlipnik Castillo', 'Juan Carlos Saez',
       'Gonzalo Lama', 'Jui Chen Hung', 'Chieh Fu Wang', 'Patrick Tierro',
       'Ruben Gonzales', 'Treat Conrad Huey', 'Francis Casey Alcantara',
       'Christopher Rungkat', 'Sunu Wahyu Trijati', 'David Agung Susanto',
       'Aditya Hari Sasongko', 'Aisam Ul Haq Qureshi', 'Mohammad Ghareeb',
       'Aqeel Khan', 'Samir Iftikhar', 'M Abid Ali Khan Akbar',
       'Jimmy Wang', 'Fritz Wolmarans', 'Cem Ilkel', 'Dzmitry Zhyrmont',
       'Egor Gerasimov', 'Joao Domingues', 'Benjamin Balleret',
       'Romain Arneodo', 'Mirza Basic', 'Tomislav Brkic', 'Benjamin Lock',
       'Marton Fucsovics', 'Gabor Borsos', 'Antso Rakotondramanga',
       'Lofo Ramiaramanana', 'Martins Podzus', 'Dimitar Kuzmanov',
       'Alexander Lazov', 'Frederico Ferreira Silva', 'Peter Nagy',
       'Dimitar Kutrovsky', 'Tihomir Grozdanov', 'Gastao Elias',
       'Tucker Vorster', 'Ruan Roelofse', 'Yassine Idmbarek',
       'Takanyi Garanganga', 'Jean Jacques Rakotohasy',
       'Sharmal Dissanayake', 'Harshana Godamanna', 'Hady Habib',
       'Shahin Khaledan', 'Abdullah Maqdas', 'Alex Diaz',
       'Federico Zeballos', 'Duilio Beretta', 'Mauricio Echazu',
       'Santiago Maresca', 'Nicolas Xiviller', 'Zhe Li'], dtype=object)

In [6]:
df.shape

(2958, 49)

In [9]:
df['winner_name'].value_counts()

Novak Djokovic                83
Andy Murray                   71
Roger Federer                 63
Rafael Nadal                  61
Tomas Berdych                 57
Kei Nishikori                 55
David Ferrer                  55
Stanislas Wawrinka            55
Kevin Anderson                46
John Isner                    45
Richard Gasquet               43
Gilles Simon                  43
Roberto Bautista Agut         42
Bernard Tomic                 40
David Goffin                  39
Joao Sousa                    38
Ivo Karlovic                  38
Steve Johnson                 37
Dominic Thiem                 36
Marin Cilic                   35
Viktor Troicki                35
Jack Sock                     35
Gael Monfils                  34
Gilles Muller                 33
Philipp Kohlschreiber         33
Milos Raonic                  33
Grigor Dimitrov               33
Jo Wilfried Tsonga            32
Fabio Fognini                 32
Guillermo Garcia Lopez        32
                              ..
Duilio Beretta                 1
Adrian Menendez Maceiras       1
Victor Hanescu                 1
Federico Zeballos              1
Santiago Maresca               1
Samir Iftikhar                 1
Julien Benneteau               1
Francis Tiafoe                 1
Aditya Hari Sasongko           1
Matteo Donati                  1
Mauricio Echazu                1
Ruan Roelofse                  1
Yassine Idmbarek               1
Peter Gojowczyk                1
Frederico Ferreira Silva       1
Jaume Munar                    1
Marat Deviatiarov              1
Andrea Arnaboldi               1
Tomislav Brkic                 1
Treat Conrad Huey              1
Sharmal Dissanayake            1
Ruben Gonzales                 1
Daniel Elahi Galan Riveros     1
Aljaz Radinski                 1
Marco Chiudinelli              1
Lofo Ramiaramanana             1
Dimitar Kutrovsky              1
Jan Mertl                      1
Kimmer Coppejans               1
Jose Rubin Statham             1
Name: winner_name, Length: 287, dtype: int64

In [10]:
df['loser_name'].value_counts()

Joao Sousa                    31
Adrian Mannarino              30
Thomaz Bellucci               30
Lukas Rosol                   30
Jiri Vesely                   30
Roberto Bautista Agut         29
Santiago Giraldo              28
Borna Coric                   28
Steve Johnson                 28
Bernard Tomic                 28
Dominic Thiem                 28
Viktor Troicki                28
Martin Klizan                 27
Simone Bolelli                27
Jeremy Chardy                 27
Sergiy Stakhovsky             27
Andreas Haider Maurer         26
Alexandr Dolgopolov           26
Fabio Fognini                 26
Fernando Verdasco             26
Feliciano Lopez               26
Pablo Cuevas                  26
David Goffin                  25
Andreas Seppi                 25
John Isner                    25
Guillermo Garcia Lopez        25
Pablo Carreno Busta           25
Ivo Karlovic                  25
Gilles Muller                 24
Jerzy Janowicz                24
                              ..
Niels Desein                   1
Daniel Elahi Galan Riveros     1
Zhizhen Zhang                  1
Tim Van Rijthoven              1
Liam Broady                    1
Andrei Soltoianu               1
Duilio Vallebuona              1
Alex Llompart                  1
Abdullah Maqdas                1
Gabriel Flores Ruiz            1
David Vega Hernandez           1
Egor Gerasimov                 1
Yaraslau Shyla                 1
Mohamed Safwat                 1
Ryan Shane                     1
Matteo Trevisan                1
David Souto                    1
Laslo Djere                    1
Daniel Garza                   1
Nicolas Barrientos             1
Patrick Tierro                 1
Andrei Ciumac                  1
Nerman Fatic                   1
Jordan Thompson                1
Eric Quigley                   1
Mehdi Jdi                      1
Federico Gaio                  1
Karim Alayli                   1
Miguel Angel Este              1
Taylor Harry Fritz             1
Name: loser_name, Length: 404, dtype: int64

In [95]:
w_fst_srv_pct_lst=[]
w_fst_srv_pct_diff_lst=[]
win_lose=[]
w_name=[]
w_age=[]
w_age_diff_lst=[]
w_height_diff=[]
w_rank=[]
w_rank_diff_lst=[]
w_scd_srv_pct_lst=[]
w_bp_saved_pct_lst=[]
w_surface=[]
for i, row in clean_two_df.iterrows():
    w_fst_srv_pct = row['w_1stWon']/row['w_svpt']#winner first serve percentage
    w_fst_srv_pct_lst.append(w_fst_srv_pct)
    l_fst_srv_pct = row['l_1stWon']/row['l_svpt']
    w_l_fst_sv_pct_diff = w_fst_srv_pct - l_fst_srv_pct#loser first serve percentage 
    w_name.append(row['winner_name'])
    w_age.append(row['winner_age'])
    w_scd_srv_pct= row['w_2ndWon']/row['w_svpt']#second serve % 
    w_scd_srv_pct_lst.append(w_scd_srv_pct)
    w_rank.append(row['winner_rank'])
    w_bp_saved_pct = row['w_bpSaved']/row['w_bpFaced']#break point saved %
    w_bp_saved_pct_lst.append(w_bp_saved_pct)
    w_rank_diff= row['winner_rank']-row['loser_rank']#rank diff
    w_rank_diff_lst.append(w_l_rank_diff)
    w_age_diff= row['winner_age']-row['loser_age']#age diff
    w_age_diff_lst.append(w_age_diff)
    win_lose.append(1)
    w_surface.append((row['surface']))
print(len(w_fst_srv_pct_lst), len(win_lose), len(w_name), len(w_age), len(w_rank), len(w_scd_srv_pct_lst), len(w_bp_saved_pct_lst), len(w_age_diff_lst),len(w_l_rank_diff_lst),len(w_surface))

1559 1559 1559 1559 1559 1559 1559 1559 1559 1559

In [40]:
len(w_fst_srv_pct_lst)

1559

In [41]:
len(clean_df)

1559

In [100]:
#match ups
df_Nadal_win = clean_two_df.loc[clean_two_df['winner_name'] == 'Rafael Nadal', 'loser_name']
df_Nadal_win

121                   Jeremy Chardy
172                    Ivo Karlovic
184                    Milos Raonic
190              Stanislas Wawrinka
218                     Lukas Rosol
230                  Kevin Anderson
355                 Thomaz Bellucci
514                 Mikhail Youzhny
692                   Igor Sijsling
712                    Donald Young
1095    Diego Sebastian Schwartzman
1477                Mikhail Youzhny
1517                    Tim Smyczek
1547                 Kevin Anderson
1608                 Carlos Berlocq
1924                Grigor Dimitrov
1965                   Marsel Ilhan
2326               Marcos Baghdatis
2424                  Fabio Fognini
2468                    Lukas Rosol
2478                Grigor Dimitrov
2483                    Marin Cilic
2486                Richard Gasquet
2559                Nicolas Almagro
2587               Andrey Kuznetsov
2601                      Jack Sock
2618             Stanislas Wawrinka
2625                   David Ferrer
Name: loser_name, dtype: object

In [101]:
df_Nadal_lose = clean_two_df.loc[clean_two_df['loser_name'] == 'Rafael Nadal', 'winner_name']
df_Nadal_lose

131         Feliciano Lopez
193      Jo Wilfried Tsonga
236      Stanislas Wawrinka
399            Dustin Brown
727            Milos Raonic
811       Fernando Verdasco
1123          Fabio Fognini
1248    Alexandr Dolgopolov
1929            Andy Murray
2109         Michael Berrer
Name: winner_name, dtype: object

In [46]:
tourney_date=[]
l_player_id=[]
w_player_id=[]
w_player_name=[]
l_player_name=[]
w_rank=[]
l_rank=[]
w_age=[]
l_age=[]
w_fst_srv_pct_lst=[]
l_fst_srv_pct_lst=[]
w_scd_srv_pct_lst=[]
l_scd_srv_pct_lst=[]
w_bp_saved_pct_lst=[]
l_bp_saved_pct_lst=[]

for i, row in clean_two_df.iterrows():
    w_fst_srv_pct = row['w_1stWon']/row['w_svpt']#winner first serve percentage
    w_fst_srv_pct_lst.append(w_fst_srv_pct)
    l_fst_srv_pct = row['l_1stWon']/row['l_svpt']
    l_fst_srv_pct_lst.append(l_fst_srv_pct)
    w_player_id.append(row['winner_id'])
    l_player_id.append(row['loser_id'])
    w_age.append(row['winner_age'])
    l_age.append(row['loser_age'])
    w_player_name.append(row['winner_name'])
    l_player_name.append(row['loser_name'])
    w_scd_srv_pct= row['w_2ndWon']/row['w_svpt']#second serve % 
    w_scd_srv_pct_lst.append(w_scd_srv_pct)
    l_scd_srv_pct= row['l_2ndWon']/row['l_svpt']
    l_scd_srv_pct_lst.append(l_scd_srv_pct)
    w_rank.append(row['winner_rank'])
    l_rank.append(row['loser_rank'])
    w_bp_saved_pct = row['w_bpSaved']/row['w_bpFaced']#break point saved %
    w_bp_saved_pct_lst.append(w_bp_saved_pct)
    l_bp_saved_pct = row['l_bpSaved']/row['l_bpFaced']
    l_bp_saved_pct_lst.append(l_bp_saved_pct)
    tourney_date.append(row['tourney_date'])
print(len(w_fst_srv_pct_lst),len(l_fst_srv_pct_lst), len(w_player_id), len(l_player_id), len(w_age), len(l_age), len(l_rank), len(w_rank), len(w_scd_srv_pct_lst), len(l_scd_srv_pct_lst),len(w_bp_saved_pct_lst), len(w_player_name), len(l_player_name),len(l_bp_saved_pct_lst),len(tourney_date))
rows= zip(tourney_date,
l_player_id,
w_player_id,
w_player_name,
l_player_name,
w_rank,
l_rank,
w_age,
l_age,
w_fst_srv_pct_lst,
l_fst_srv_pct_lst,
w_scd_srv_pct_lst,
l_scd_srv_pct_lst,
w_bp_saved_pct_lst,
l_bp_saved_pct_lst
)
headers=['tourney_date',
'loser_player_id',
'winner_player_id',
'w_player_name',
'l_player_name',
'winner_rank',
'loser_rank',
'winner_age',
'loser_age',
'w_fst_srv_pct',
'l_fst_srv_pct',
'w_scd_srv_pct',
'l_scd_srv_pct',
'w_bp_saved_pct',
'l_bp_saved_pct']

1559 1559 1559 1559 1559 1559 1559 1559 1559 1559 1559 1559 1559 1559 1559

In [47]:

csvfile = "/Users/forrestbadgley/Documents/DataScience/Homework/FinalProject/pre_processed/tennis_2015_processed.csv"

with open(csvfile, "w") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    for row in rows:
        writer.writerow(row)

In [51]:

df = pd.read_csv('pre_processed/tennis_2015_processed.csv')
df.head(10)

,tourney_date,loser_player_id,winner_player_id,w_player_name,l_player_name,winner_rank,loser_rank,winner_age,loser_age,w_fst_srv_pct,l_fst_srv_pct,w_scd_srv_pct,l_scd_srv_pct,w_bp_saved_pct,l_bp_saved_pct
0,20151005,106415,105147,Tatsuma Ito,Yoshihito Nishioka,127.0,148.0,27.381246,20.021903,0.290323,0.260417,0.268817,0.239583,0.642857,0.631579
1,20151005,105051,105572,Austin Krajicek,Matthew Ebden,124.0,131.0,25.303217,27.857632,0.507812,0.468750,0.171875,0.210938,0.571429,0.818182
2,20151005,103852,105311,Joao Sousa,Feliciano Lopez,45.0,15.0,26.516085,34.039699,0.457831,0.317647,0.204819,0.247059,0.666667,0.500000
3,20151005,104731,104180,Gilles Muller,Kevin Anderson,43.0,12.0,32.407940,29.382615,0.407407,0.326087,0.314815,0.195652,1.000000,0.400000
4,20151005,105777,105332,Benoit Paire,Grigor Dimitrov,32.0,21.0,26.409309,24.388775,0.423913,0.506849,0.228261,0.136986,0.923077,0.250000
5,20151005,105077,106401,Nick Kyrgios,Albert Ramos,34.0,71.0,20.440794,27.715264,0.454545,0.409524,0.250000,0.190476,0.500000,0.733333
6,20151005,104755,105138,Roberto Bautista Agut,Richard Gasquet,22.0,11.0,27.474333,29.297741,0.386364,0.301587,0.227273,0.174603,0.600000,0.538462
7,20151005,105385,105227,Marin Cilic,Donald Young,14.0,51.0,27.017112,26.201232,0.408696,0.341085,0.208696,0.240310,0.666667,0.714286
8,20151005,106071,105449,Steve Johnson,Bernard Tomic,48.0,20.0,25.779603,22.954141,0.451613,0.325000,0.258065,0.150000,0.500000,0.500000
9,20151005,106432,105453,Kei Nishikori,Borna Coric,6.0,38.0,25.765914,18.888433,0.349398,0.400000,0.265060,0.129412,0.800000,0.666667

In [74]:
df_2014 = pd.read_csv('tennis_2014.csv')
df_2014.head(10)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2014-301,Auckland,Hard,28,A,20140106,1,105385,NaN,Q,...,3.0,2.0,2.0,82.0,59.0,33.0,12.0,10.0,9.0,13.0
1,2014-301,Auckland,Hard,28,A,20140106,2,105053,NaN,NaN,...,3.0,1.0,4.0,68.0,38.0,27.0,10.0,10.0,6.0,10.0
2,2014-301,Auckland,Hard,28,A,20140106,3,104198,NaN,NaN,...,7.0,7.0,4.0,100.0,72.0,54.0,10.0,17.0,0.0,3.0
3,2014-301,Auckland,Hard,28,A,20140106,4,105449,NaN,LL,...,2.0,8.0,7.0,105.0,63.0,47.0,22.0,17.0,4.0,7.0
4,2014-301,Auckland,Hard,28,A,20140106,5,104229,NaN,NaN,...,3.0,11.0,2.0,76.0,36.0,30.0,18.0,12.0,4.0,7.0
5,2014-301,Auckland,Hard,28,A,20140106,6,105614,NaN,Q,...,7.0,8.0,4.0,110.0,83.0,56.0,12.0,15.0,13.0,15.0
6,2014-301,Auckland,Hard,28,A,20140106,7,104259,5.0,NaN,...,2.0,4.0,5.0,88.0,56.0,40.0,14.0,15.0,3.0,7.0
7,2014-301,Auckland,Hard,28,A,20140106,8,104547,NaN,NaN,...,5.0,2.0,2.0,64.0,41.0,23.0,7.0,9.0,4.0,9.0
8,2014-301,Auckland,Hard,28,A,20140106,9,105041,NaN,Q,...,4.0,3.0,3.0,66.0,44.0,25.0,7.0,8.0,7.0,11.0
9,2014-301,Auckland,Hard,28,A,20140106,10,105332,6.0,NaN,...,0.0,2.0,2.0,57.0,33.0,24.0,11.0,9.0,3.0,6.0

In [69]:
for cell in df_2014['w_svpt']:
	if cell  == 0:
		print("zero in cell")

zero in cell

In [77]:
clean_df_2014=df_2014[(df_2014 != 0).all(1)]
clean_df_2014.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2014-301,Auckland,Hard,28,A,20140106,1,105385,NaN,Q,...,3.0,2.0,2.0,82.0,59.0,33.0,12.0,10.0,9.0,13.0
1,2014-301,Auckland,Hard,28,A,20140106,2,105053,NaN,NaN,...,3.0,1.0,4.0,68.0,38.0,27.0,10.0,10.0,6.0,10.0
3,2014-301,Auckland,Hard,28,A,20140106,4,105449,NaN,LL,...,2.0,8.0,7.0,105.0,63.0,47.0,22.0,17.0,4.0,7.0
4,2014-301,Auckland,Hard,28,A,20140106,5,104229,NaN,NaN,...,3.0,11.0,2.0,76.0,36.0,30.0,18.0,12.0,4.0,7.0
5,2014-301,Auckland,Hard,28,A,20140106,6,105614,NaN,Q,...,7.0,8.0,4.0,110.0,83.0,56.0,12.0,15.0,13.0,15.0

In [78]:
clean_df_2014['full_count'] = clean_df_2014.apply(lambda x: x.count(), axis=1)
clean_df_2014

/Users/forrestbadgley/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,full_count
0,2014-301,Auckland,Hard,28,A,20140106,1,105385,NaN,Q,...,2.0,2.0,82.0,59.0,33.0,12.0,10.0,9.0,13.0,46
1,2014-301,Auckland,Hard,28,A,20140106,2,105053,NaN,NaN,...,1.0,4.0,68.0,38.0,27.0,10.0,10.0,6.0,10.0,45
3,2014-301,Auckland,Hard,28,A,20140106,4,105449,NaN,LL,...,8.0,7.0,105.0,63.0,47.0,22.0,17.0,4.0,7.0,47
4,2014-301,Auckland,Hard,28,A,20140106,5,104229,NaN,NaN,...,11.0,2.0,76.0,36.0,30.0,18.0,12.0,4.0,7.0,45
5,2014-301,Auckland,Hard,28,A,20140106,6,105614,NaN,Q,...,8.0,4.0,110.0,83.0,56.0,12.0,15.0,13.0,15.0,47
7,2014-301,Auckland,Hard,28,A,20140106,8,104547,NaN,NaN,...,2.0,2.0,64.0,41.0,23.0,7.0,9.0,4.0,9.0,45
8,2014-301,Auckland,Hard,28,A,20140106,9,105041,NaN,Q,...,3.0,3.0,66.0,44.0,25.0,7.0,8.0,7.0,11.0,47
10,2014-301,Auckland,Hard,28,A,20140106,11,105138,NaN,NaN,...,1.0,2.0,87.0,46.0,30.0,20.0,13.0,4.0,8.0,45
12,2014-301,Auckland,Hard,28,A,20140106,13,103970,1.0,NaN,...,1.0,2.0,89.0,60.0,35.0,12.0,14.0,6.0,13.0,47
13,2014-301,Auckland,Hard,28,A,20140106,14,104198,NaN,NaN,...,5.0,2.0,94.0,50.0,29.0,20.0,14.0,5.0,12.0,45
14,2014-301,Auckland,Hard,28,A,20140106,15,105449,NaN,LL,...,11.0,2.0,57.0,34.0,23.0,17.0,11.0,4.0,6.0,47
15,2014-301,Auckland,Hard,28,A,20140106,16,104229,NaN,NaN,...,8.0,1.0,80.0,51.0,38.0,15.0,14.0,2.0,6.0,46
17,2014-301,Auckland,Hard,28,A,20140106,18,104545,3.0,NaN,...,5.0,3.0,102.0,53.0,36.0,28.0,15.0,6.0,8.0,47
19,2014-301,Auckland,Hard,28,A,20140106,20,106058,NaN,WC,...,3.0,1.0,57.0,32.0,23.0,14.0,10.0,2.0,5.0,47
22,2014-301,Auckland,Hard,28,A,20140106,23,104545,3.0,NaN,...,8.0,1.0,140.0,87.0,61.0,40.0,18.0,7.0,7.0,47
23,2014-301,Auckland,Hard,28,A,20140106,24,105138,NaN,NaN,...,4.0,2.0,50.0,30.0,21.0,5.0,8.0,4.0,8.0,45
25,2014-301,Auckland,Hard,28,A,20140106,26,104545,3.0,NaN,...,5.0,1.0,102.0,74.0,49.0,19.0,16.0,5.0,7.0,45
26,2014-301,Auckland,Hard,28,A,20140106,27,104545,3.0,NaN,...,5.0,1.0,93.0,62.0,45.0,19.0,12.0,10.0,10.0,46
27,2014-403,Miami Masters,Hard,96,M,20140319,1,103720,NaN,NaN,...,7.0,5.0,102.0,55.0,36.0,23.0,14.0,4.0,8.0,45
29,2014-403,Miami Masters,Hard,96,M,20140319,3,105138,NaN,NaN,...,17.0,2.0,101.0,65.0,41.0,15.0,13.0,9.0,13.0,45
32,2014-403,Miami Masters,Hard,96,M,20140319,6,104198,NaN,NaN,...,6.0,3.0,68.0,35.0,24.0,19.0,12.0,2.0,5.0,45
33,2014-403,Miami Masters,Hard,96,M,20140319,7,105379,NaN,Q,...,3.0,2.0,87.0,50.0,32.0,17.0,13.0,1.0,5.0,47
34,2014-403,Miami Masters,Hard,96,M,20140319,8,105992,NaN,WC,...,2.0,3.0,59.0,39.0,19.0,12.0,9.0,7.0,11.0,46
35,2014-403,Miami Masters,Hard,96,M,20140319,9,104593,NaN,NaN,...,5.0,4.0,94.0,52.0,33.0,18.0,13.0,6.0,12.0,45
36,2014-403,Miami Masters,Hard,96,M,20140319,10,104273,NaN,NaN,...,10.0,1.0,99.0,56.0,46.0,22.0,15.0,8.0,9.0,45
39,2014-403,Miami Masters,Hard,96,M,20140319,13,105385,NaN,NaN,...,1.0,3.0,54.0,33.0,17.0,7.0,8.0,2.0,7.0,45
40,2014-403,Miami Masters,Hard,96,M,20140319,14,105023,NaN,NaN,...,4.0,3.0,72.0,44.0,31.0,15.0,11.0,8.0,10.0,45
44,2014-403,Miami Masters,Hard,96,M,20140319,18,105217,NaN,Q,...,1.0,1.0,58.0,39.0,23.0,9.0,8.0,3.0,6.0,46
45,2014-403,Miami Masters,Hard,96,M,20140319,19,104547,NaN,NaN,...,6.0,2.0,49.0,28.0,19.0,10.0,10.0,2.0,6.0,46
46,2014-403,Miami Masters,Hard,96,M,20140319,20,105292,NaN,NaN,...,4.0,3.0,65.0,37.0,25.0,15.0,10.0,3.0,6.0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2871,2014-D072,Davis Cup G2 R2: MDA vs BLR,Clay,4,D,20140404,3,105430,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2872,2014-D072,Davis Cup G2 R2: MDA vs BLR,Clay,4,D,20140404,4,106201,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2873,2014-D073,Davis Cup G2 R2: DEN vs LUX,Hard,4,D,20140404,1,104952,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2874,2014-D073,Davis Cup G2 R2: DEN vs LUX,Hard,4,D,20140404,2,104233,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2875,2014-D073,Davis Cup G2 R2: DEN vs LUX,Hard,4,D,20140404,3,104233,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2876,2014-D073,Davis Cup G2 R2: DEN vs LUX,Hard,4,D,20140404,4,111453,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
2877,2014-D074,Davis Cup G2 R3: BIH vs LTU,Hard,4,D,20140912,1,105575,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2878,2014-D074,Davis Cup G2 R3: BIH vs LTU,Hard,4,D,20140912,2,106000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
2879,2014-D074,Davis Cup G2 R3: BIH vs LTU,Hard,4,D,20140912,3,105575,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
2880,2014-D074,Davis Cup G2 R3: BIH vs LTU,Hard,4,D,20140912,4,123983,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2881,2014-D075,Davis Cup G2 R3: DEN vs MDA,NaN,4,D,20140912,1,105430,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
2882,2014-D075,Davis Cup G2 R3: DEN vs MDA,NaN,4,D,20140912,2,104233,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2883,2014-D075,Davis Cup G2 R3: DEN vs MDA,NaN,4,D,20140912,3,105430,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2884,2014-D075,Davis Cup G2 R3: DEN vs MDA,NaN,4,D,20140912,4,104952,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
2885,2014-D076,Davis Cup G2 PO: NOR vs MON,Hard,4,D,20140404,1,104112,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2886,2014-D076,Davis Cup G2 PO: NOR vs MON,Hard,4,D,20140404,2,106033,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2887,2014-D076,Davis Cup G2 PO: NOR vs MON,Hard,4,D,20140404,3,104112,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2888,2014-D076,Davis Cup G2 PO: NOR vs MON,Hard,4,D,20140404,4,106033,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2889,2014-D077,Davis Cup G2 PO: GRE vs BUL,Clay,4,D,20140404,1,105777,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2890,2014-D077,Davis Cup G2 PO: GRE vs BUL,Clay,4,D,20140404,2,105004,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2891,2014-D077,Davis Cup G2 PO: GRE vs BUL,Clay,4,D,20140404,3,103891,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2892,2014-D077,Davis Cup G2 PO: GRE vs BUL,Clay,4,D,20140404,4,105004,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2893,2014-D078,Davis Cup G2 PO: IRL vs EGY,Hard,4,D,20140404,1,104945,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2894,2014-D078,Davis Cup G2 PO: IRL vs EGY,Hard,4,D,20140404,2,105633,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2895,2014-D078,Davis Cup G2 PO: IRL vs EGY,Hard,4,D,20140404,3,104945,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2896,2014-D078,Davis Cup G2 PO: IRL vs EGY,Hard,4,D,20140404,4,106387,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2897,2014-D079,Davis Cup G2 PO: MAR vs CYP,Clay,4,D,20140404,1,108749,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
2898,2014-D079,Davis Cup G2 PO: MAR vs CYP,Clay,4,D,20140404,2,104467,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
2899,2014-D079,Davis Cup G2 PO: MAR vs CYP,Clay,4,D,20140404,3,104467,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2900,2014-D079,Davis Cup G2 PO: MAR vs CYP,Clay,4,D,20140404,4,109336,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21

In [81]:
clean_df_2014= clean_df_2014[np.isfinite(clean_df_2014['w_svpt'])]
clean_df_2014

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,full_count
0,2014-301,Auckland,Hard,28,A,20140106,1,105385,NaN,Q,...,2.0,2.0,82.0,59.0,33.0,12.0,10.0,9.0,13.0,46
1,2014-301,Auckland,Hard,28,A,20140106,2,105053,NaN,NaN,...,1.0,4.0,68.0,38.0,27.0,10.0,10.0,6.0,10.0,45
3,2014-301,Auckland,Hard,28,A,20140106,4,105449,NaN,LL,...,8.0,7.0,105.0,63.0,47.0,22.0,17.0,4.0,7.0,47
4,2014-301,Auckland,Hard,28,A,20140106,5,104229,NaN,NaN,...,11.0,2.0,76.0,36.0,30.0,18.0,12.0,4.0,7.0,45
5,2014-301,Auckland,Hard,28,A,20140106,6,105614,NaN,Q,...,8.0,4.0,110.0,83.0,56.0,12.0,15.0,13.0,15.0,47
7,2014-301,Auckland,Hard,28,A,20140106,8,104547,NaN,NaN,...,2.0,2.0,64.0,41.0,23.0,7.0,9.0,4.0,9.0,45
8,2014-301,Auckland,Hard,28,A,20140106,9,105041,NaN,Q,...,3.0,3.0,66.0,44.0,25.0,7.0,8.0,7.0,11.0,47
10,2014-301,Auckland,Hard,28,A,20140106,11,105138,NaN,NaN,...,1.0,2.0,87.0,46.0,30.0,20.0,13.0,4.0,8.0,45
12,2014-301,Auckland,Hard,28,A,20140106,13,103970,1.0,NaN,...,1.0,2.0,89.0,60.0,35.0,12.0,14.0,6.0,13.0,47
13,2014-301,Auckland,Hard,28,A,20140106,14,104198,NaN,NaN,...,5.0,2.0,94.0,50.0,29.0,20.0,14.0,5.0,12.0,45
14,2014-301,Auckland,Hard,28,A,20140106,15,105449,NaN,LL,...,11.0,2.0,57.0,34.0,23.0,17.0,11.0,4.0,6.0,47
15,2014-301,Auckland,Hard,28,A,20140106,16,104229,NaN,NaN,...,8.0,1.0,80.0,51.0,38.0,15.0,14.0,2.0,6.0,46
17,2014-301,Auckland,Hard,28,A,20140106,18,104545,3.0,NaN,...,5.0,3.0,102.0,53.0,36.0,28.0,15.0,6.0,8.0,47
19,2014-301,Auckland,Hard,28,A,20140106,20,106058,NaN,WC,...,3.0,1.0,57.0,32.0,23.0,14.0,10.0,2.0,5.0,47
22,2014-301,Auckland,Hard,28,A,20140106,23,104545,3.0,NaN,...,8.0,1.0,140.0,87.0,61.0,40.0,18.0,7.0,7.0,47
23,2014-301,Auckland,Hard,28,A,20140106,24,105138,NaN,NaN,...,4.0,2.0,50.0,30.0,21.0,5.0,8.0,4.0,8.0,45
25,2014-301,Auckland,Hard,28,A,20140106,26,104545,3.0,NaN,...,5.0,1.0,102.0,74.0,49.0,19.0,16.0,5.0,7.0,45
26,2014-301,Auckland,Hard,28,A,20140106,27,104545,3.0,NaN,...,5.0,1.0,93.0,62.0,45.0,19.0,12.0,10.0,10.0,46
27,2014-403,Miami Masters,Hard,96,M,20140319,1,103720,NaN,NaN,...,7.0,5.0,102.0,55.0,36.0,23.0,14.0,4.0,8.0,45
29,2014-403,Miami Masters,Hard,96,M,20140319,3,105138,NaN,NaN,...,17.0,2.0,101.0,65.0,41.0,15.0,13.0,9.0,13.0,45
32,2014-403,Miami Masters,Hard,96,M,20140319,6,104198,NaN,NaN,...,6.0,3.0,68.0,35.0,24.0,19.0,12.0,2.0,5.0,45
33,2014-403,Miami Masters,Hard,96,M,20140319,7,105379,NaN,Q,...,3.0,2.0,87.0,50.0,32.0,17.0,13.0,1.0,5.0,47
34,2014-403,Miami Masters,Hard,96,M,20140319,8,105992,NaN,WC,...,2.0,3.0,59.0,39.0,19.0,12.0,9.0,7.0,11.0,46
35,2014-403,Miami Masters,Hard,96,M,20140319,9,104593,NaN,NaN,...,5.0,4.0,94.0,52.0,33.0,18.0,13.0,6.0,12.0,45
36,2014-403,Miami Masters,Hard,96,M,20140319,10,104273,NaN,NaN,...,10.0,1.0,99.0,56.0,46.0,22.0,15.0,8.0,9.0,45
39,2014-403,Miami Masters,Hard,96,M,20140319,13,105385,NaN,NaN,...,1.0,3.0,54.0,33.0,17.0,7.0,8.0,2.0,7.0,45
40,2014-403,Miami Masters,Hard,96,M,20140319,14,105023,NaN,NaN,...,4.0,3.0,72.0,44.0,31.0,15.0,11.0,8.0,10.0,45
44,2014-403,Miami Masters,Hard,96,M,20140319,18,105217,NaN,Q,...,1.0,1.0,58.0,39.0,23.0,9.0,8.0,3.0,6.0,46
45,2014-403,Miami Masters,Hard,96,M,20140319,19,104547,NaN,NaN,...,6.0,2.0,49.0,28.0,19.0,10.0,10.0,2.0,6.0,46
46,2014-403,Miami Masters,Hard,96,M,20140319,20,105292,NaN,NaN,...,4.0,3.0,65.0,37.0,25.0,15.0,10.0,3.0,6.0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2543,2014-341,Metz,Hard,28,A,20140915,17,105311,6.0,NaN,...,12.0,3.0,98.0,53.0,39.0,24.0,15.0,1.0,3.0,45
2544,2014-341,Metz,Hard,28,A,20140915,18,103908,NaN,WC,...,9.0,1.0,74.0,42.0,31.0,14.0,9.0,10.0,12.0,47
2546,2014-341,Metz,Hard,28,A,20140915,20,104792,2.0,NaN,...,3.0,4.0,69.0,45.0,27.0,7.0,10.0,4.0,9.0,47
2547,2014-341,Metz,Hard,28,A,20140915,21,105676,8.0,NaN,...,17.0,5.0,103.0,62.0,49.0,23.0,16.0,6.0,8.0,47
2551,2014-341,Metz,Hard,28,A,20140915,25,105676,8.0,NaN,...,12.0,2.0,69.0,43.0,32.0,11.0,10.0,2.0,4.0,45
2552,2014-341,Metz,Hard,28,A,20140915,26,105311,6.0,NaN,...,13.0,2.0,63.0,34.0,26.0,13.0,10.0,2.0,5.0,46
2554,2014-440,s-Hertogenbosch,Grass,32,A,20140615,1,105311,NaN,Q,...,3.0,2.0,92.0,56.0,32.0,15.0,13.0,5.0,11.0,46
2556,2014-440,s-Hertogenbosch,Grass,32,A,20140615,3,105217,NaN,WC,...,4.0,5.0,74.0,49.0,35.0,10.0,11.0,1.0,4.0,46
2557,2014-440,s-Hertogenbosch,Grass,32,A,20140615,4,104098,5.0,NaN,...,6.0,5.0,69.0,44.0,30.0,12.0,10.0,5.0,7.0,46
2558,2014-440,s-Hertogenbosch,Grass,32,A,20140615,5,103794,NaN,NaN,...,9.0,3.0,94.0,66.0,44.0,11.0,14.0,7.0,10.0,46
2561,2014-440,s-Hertogenbosch,Grass,32,A,20140615,8,105577,6.0,NaN,...,3.0,1.0,63.0,46.0,31.0,9.0,11.0,4.0,6.0,46
2562,2014-440,s-Hertogenbosch,Grass,32,A,20140615,9,103917,7.0,NaN,...,4.0,3.0,81.0,51.0,33.0,18.0,13.0,6.0,9.0,46
2563,2014-440,s-Hertogenbosch,Grass,32,A,20140615,10,105449,NaN,NaN,...,15.0,1.0,79.0,54.0,39.0,15.0,12.0,3.0,4.0,45
2564,2014-440,s-Hertogenbosch,Grass,32,A,20140615,11,105051,NaN,NaN,...,9.0,3.0,72.0,51.0,35.0,9.0,14.0,5.0,10.0,46
2566,2014-440,s-Hertogenbosch,Grass,32,A,20140615,13,103781,8.0,NaN,...,2.0,2.0,69.0,40.0,18.0,12.0,10.0,11.0,17.0,46
2569,2014-440,s-Hertogenbosch,Grass,32,A,20140615,16,104269,2.0,NaN,...,5.0,3.0,78.0,51.0,39.0,15.0,14.0,4.0,6.0,46
2572,2014-440,s-Hertogenbosch,Grass,32,A,20140615,19,103794,NaN,NaN,...,1.0,2.0,76.0,45.0,19.0,12.0,10.0,6.0,13.0,45
2573,2014-440,s-Hertogenbosch,Grass,32,A,20140615,20,105577,6.0,NaN,...,2.0,1.0,53.0,35.0,21.0,9.0,9.0,2.0,6.0,45
2577,2014-440,s-Hertogenbosch,Grass,32,A,20140615,24,104269,2.0,NaN,...,3.0,1.0,55.0,37.0,25.0,11.0,10.0,4.0,6.0,47
2578,2014-440,s-Hertogenbosch,Grass,32,A,20140615,25,105311,NaN,Q,...,5.0,1.0,50.0,32.0,23.0,5.0,9.0,3.0,6.0,46
2579,2014-440,s-Hertogenbosch,Grass,32,A,20140615,26,103794,NaN,NaN,...,13.0,6.0,123.0,72.0,49.0,33.0,17.0,7.0,9.0,46
2581,2014-440,s-Hertogenbosch,Grass,32,A,20140615,28,103781,8.0,NaN,...,11.0,9.0,144.0,89.0,68.0,24.0,18.0,7.0,9.0,47
2582,2014-440,s-Hertogenbosch,Grass,32,A,20140615,29,103794,NaN,NaN,...,6.0,1.0,60.0,42.0,29.0,9.0,10.0,2.0,4.0,45
2583,2014-440,s-Hertogenbosch,Grass,32,A,20140615,30,105138,3.0,NaN,...,6.0,6.0,95.0,67.0,44.0,15.0,15.0,5.0,8.0,46
2589,2014-605,Tour Finals,Hard,8,F,20141109,5,104527,3.0,NaN,...,7.0,4.0,86.0,54.0,42.0,10.0,14.0,4.0,8.0,47
2591,2014-605,Tour Finals,Hard,8,F,20141109,7,103819,2.0,NaN,...,1.0,5.0,52.0,28.0,19.0,11.0,8.0,4.0,7.0,47
2593,2014-605,Tour Finals,Hard,8,F,20141109,9,105453,4.0,NaN,...,7.0,3.0,62.0,36.0,27.0,7.0,10.0,4.0,8.0,47
2594,2014-605,Tour Finals,Hard,8,F,20141109,10,105453,4.0,NaN,...,2.0,3.0,88.0,48.0,30.0,20.0,14.0,4.0,9.0,47
2595,2014-605,Tour Finals,Hard,8,F,20141109,11,103819,2.0,NaN,...,10.0,2.0,60.0,28.0,22.0,15.0,9.0,4.0,6.0,47
2597,2014-605,Tour Finals,Hard,8,F,20141109,14,104925,1.0,NaN,...,3.0,6.0,67.0,38.0,29.0,5.0,11.0,3.0,9.0,47

In [57]:
tourney_date=[]
l_player_id=[]
w_player_id=[]
w_player_name=[]
l_player_name=[]
w_rank=[]
l_rank=[]
w_age=[]
l_age=[]
w_fst_srv_pct_lst=[]
l_fst_srv_pct_lst=[]
w_scd_srv_pct_lst=[]
l_scd_srv_pct_lst=[]
w_bp_saved_pct_lst=[]
l_bp_saved_pct_lst=[]

for i, row in clean_df_2014.iterrows():
    w_fst_srv_pct = row['w_1stWon']/row['w_svpt']#winner first serve percentage
    w_fst_srv_pct_lst.append(w_fst_srv_pct)
    l_fst_srv_pct = row['l_1stWon']/row['l_svpt']
    l_fst_srv_pct_lst.append(l_fst_srv_pct)
    w_player_id.append(row['winner_id'])
    l_player_id.append(row['loser_id'])
    w_age.append(row['winner_age'])
    l_age.append(row['loser_age'])
    w_player_name.append(row['winner_name'])
    l_player_name.append(row['loser_name'])
    w_scd_srv_pct= row['w_2ndWon']/row['w_svpt']#second serve % 
    w_scd_srv_pct_lst.append(w_scd_srv_pct)
    l_scd_srv_pct= row['l_2ndWon']/row['l_svpt']
    l_scd_srv_pct_lst.append(l_scd_srv_pct)
    w_rank.append(row['winner_rank'])
    l_rank.append(row['loser_rank'])
    w_bp_saved_pct = row['w_bpSaved']/row['w_bpFaced']#break point saved %
    w_bp_saved_pct_lst.append(w_bp_saved_pct)
    l_bp_saved_pct = row['l_bpSaved']/row['l_bpFaced']
    l_bp_saved_pct_lst.append(l_bp_saved_pct)
    tourney_date.append(row['tourney_date'])
print(len(w_fst_srv_pct_lst),len(l_fst_srv_pct_lst), len(w_player_id), len(l_player_id), len(w_age), len(l_age), len(l_rank), len(w_rank), len(w_scd_srv_pct_lst), len(l_scd_srv_pct_lst),len(w_bp_saved_pct_lst), len(w_player_name), len(l_player_name),len(l_bp_saved_pct_lst),len(tourney_date))
rows= zip(tourney_date,
l_player_id,
w_player_id,
w_player_name,
l_player_name,
w_rank,
l_rank,
w_age,
l_age,
w_fst_srv_pct_lst,
l_fst_srv_pct_lst,
w_scd_srv_pct_lst,
l_scd_srv_pct_lst,
w_bp_saved_pct_lst,
l_bp_saved_pct_lst
)
headers=['tourney_date',
'loser_player_id',
'winner_player_id',
'w_player_name',
'l_player_name',
'winner_rank',
'loser_rank',
'winner_age',
'loser_age',
'w_fst_srv_pct',
'l_fst_srv_pct',
'w_scd_srv_pct',
'l_scd_srv_pct',
'w_bp_saved_pct',
'l_bp_saved_pct']

1834 1834 1834 1834 1834 1834 1834 1834 1834 1834 1834 1834 1834 1834 1834

In [58]:
csvfile = "/Users/forrestbadgley/Documents/DataScience/Homework/FinalProject/pre_processed/tennis_2014_processed.csv"

with open(csvfile, "w") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    for row in rows:
        writer.writerow(row)

In [59]:
df = pd.read_csv('pre_processed/tennis_2014_processed.csv')
df.head(10)

,tourney_date,loser_player_id,winner_player_id,w_player_name,l_player_name,winner_rank,loser_rank,winner_age,loser_age,w_fst_srv_pct,l_fst_srv_pct,w_scd_srv_pct,l_scd_srv_pct,w_bp_saved_pct,l_bp_saved_pct
0,20140106,105643,105385,Donald Young,Federico Delbonis,96.0,54.0,24.457221,23.255305,0.559322,0.402439,0.152542,0.146341,0.666667,0.692308
1,20140106,103656,105053,Santiago Giraldo,Albert Montanes,68.0,59.0,26.110883,33.111567,0.476190,0.397059,0.174603,0.147059,0.666667,0.600000
2,20140106,104571,105449,Steve Johnson,Marcos Baghdatis,160.0,109.0,24.035592,28.555784,0.427184,0.447619,0.271845,0.209524,0.500000,0.571429
3,20140106,104997,104229,Yen Hsun Lu,Igor Sijsling,62.0,69.0,30.398357,26.387406,0.447368,0.394737,0.210526,0.236842,0.333333,0.571429
4,20140106,104978,105614,Bradley Klahn,Daniel Brands,95.0,57.0,23.381246,26.475017,0.543689,0.509091,0.126214,0.109091,0.857143,0.866667
5,20140106,103835,104547,Horacio Zeballos,Filippo Volandri,66.0,70.0,28.695414,32.336756,0.422535,0.359375,0.169014,0.109375,0.600000,0.444444
6,20140106,104907,105041,Lukas Lacko,Jose Rubin Statham,90.0,288.0,26.176591,26.702259,0.452830,0.378788,0.207547,0.106061,1.000000,0.636364
7,20140106,104593,105138,Roberto Bautista Agut,Daniel Gimeno Traver,73.0,80.0,25.730322,28.416153,0.539474,0.344828,0.157895,0.229885,0.500000,0.500000
8,20140106,105385,103970,David Ferrer,Donald Young,3.0,96.0,31.764545,24.457221,0.436893,0.393258,0.174757,0.134831,0.769231,0.461538
9,20140106,105053,104198,Guillermo Garcia Lopez,Santiago Giraldo,58.0,68.0,30.592745,26.110883,0.423729,0.308511,0.161017,0.212766,0.789474,0.416667